name: Continuous Delivery
# This workflow is triggered on pushes to the repository.
on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build Docker Image and Push to Amazon ECR
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          path: main
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
      - name: Build, tag, and push image to Amazon ECR
        id: build-push
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ${{ secrets.AWS_ECR_REPOSITORY }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          IMAGE_URI=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          docker build -t $IMAGE_URI $GITHUB_WORKSPACE/main
          docker push $IMAGE_URI
          echo "::set-output name=IMAGE_URI::$IMAGE_URI"
      - name: Checkout Terraform Repo
        uses: actions/checkout@v2
        with:
          repository: ${{ secrets.TERRAFORM_REPO_ORG }}/${{ secrets.TERRAFORM_REPO_NAME }}
          ssh-key: ${{ secrets.TERRAFORM_DEPLOY_KEY }}
          path: ${{ secrets.TERRAFORM_REPO_NAME }}
      - name: Update Dev Environment with new Image Tag
        env:
          IMAGE_URI: ${{ steps.build-push.outputs.IMAGE_URI }}
          TERRAFORM_REPO_NAME: ${{ secrets.TERRAFORM_REPO_NAME }}
          TERRAFORM_REPO_VERSION_PATH: ${{ secrets.TERRAFORM_REPO_VERSION_PATH }}
        run: |
          git config --global user.email "github-actions@bitmatica.com"
          git config --global user.name "github actions"
          cd $GITHUB_WORKSPACE/$TERRAFORM_REPO_NAME
          echo -n "$IMAGE_URI" > $TERRAFORM_REPO_VERSION_PATH
          git add $TERRAFORM_REPO_VERSION_PATH
          git commit -m "$GITHUB_REPOSITORY: update dev version to $IMAGE_URI"
          git push origin master
          echo "Dev version updated in terraform.  See terraform repo's github actions for deploy progress."
      - name: Logout of Amazon ECR
        if: always()
        run: docker logout ${{ steps.login-ecr.outputs.registry }}
